// <auto-generated />
using System;
using Inventory_DAL.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryAPI.Migrations.CJCSMInventoryMigrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20230926182202_20230926_InitialCreate")]
    partial class _20230926InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventory_DAL.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address1")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Address2")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("City")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("DateOfCreation")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateOfLastUpdate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("ProvinceState")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Inventory_DAL.Entities.Pipe", b =>
                {
                    b.Property<Guid>("PipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Length")
                        .HasColumnType("real");

                    b.Property<Guid>("PipeDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("TierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PipeId");

                    b.ToTable("Pipe");
                });

            modelBuilder.Entity("Inventory_DAL.Entities.PipeDefinition", b =>
                {
                    b.Property<Guid>("PipeDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PipeCoatingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PipeConditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PipeGradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PipeSizeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PipeThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("WallSizeMetric")
                        .HasColumnType("real");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("PipeDefinitionId");

                    b.ToTable("PipeDefinition");
                });

            modelBuilder.Entity("Inventory_DAL.Entities.Rack", b =>
                {
                    b.Property<Guid>("RackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ShopLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RackId");

                    b.ToTable("Rack");
                });

            modelBuilder.Entity("Inventory_DAL.Entities.ShopLocation", b =>
                {
                    b.Property<Guid>("ShopLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address1")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Address2")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("City")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("ProvinceState")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("ShopLocationId");

                    b.ToTable("ShopLocation");
                });

            modelBuilder.Entity("Inventory_DAL.Entities.Tally", b =>
                {
                    b.Property<Guid>("TallyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CarrierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateOfCreation")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShopLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TalliedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TallyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TallyType")
                        .HasColumnType("int");

                    b.HasKey("TallyId");

                    b.ToTable("Tally");
                });

            modelBuilder.Entity("Inventory_DAL.Entities.TallyPipe", b =>
                {
                    b.Property<Guid>("TallyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PipeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TallyId", "PipeId");

                    b.ToTable("TallyPipe");
                });

            modelBuilder.Entity("Inventory_DAL.Entities.Tier", b =>
                {
                    b.Property<Guid>("TierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<Guid>("RackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TierId");

                    b.ToTable("Tier");
                });
#pragma warning restore 612, 618
        }
    }
}
